name: Build Segment Display to Pages

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node.js with node_modules cache
        uses: magnetikonline/action-node-modules-cache@v1
      - name: NPM Install
        run: npm install
      - name: Build
        run: npm run build
